######################################################################
##
## Filename: test_core.udo
## Created on: Mon Nov 20 09:47:17 AM CET 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
