webtalk_init -webtalk_dir /tp/xph3sle/xph3sle603/Security_lab/AES/synth/vivado/aes_ddr/aes_ddr.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2017-11-20 12:17:24" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174170201_174170202_210646199_166" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ocq8bdgsl6coh93j8atl6pb76k" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.1_1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "unknown" -context "user_environment"
webtalk_add_data -client project -key os_release -value "unknown" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "800.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1511176389000" -context "sdk\\\\hardware/1511176389000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1511176389000"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1511176389000"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1511176389000"
webtalk_add_data -client sdk -key VivadoVersion -value "2017.1" -context "sdk\\\\hardware/1511176389000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1511176389000"
webtalk_add_data -client sdk -key Device -value "7z010" -context "sdk\\\\hardware/1511176389000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1511176389000"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1511176389000"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1511176389000"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1511176389000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1511176644719"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1511176644719"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1511176644719"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1511176644719"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1511176644719"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1511176644719"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1511176644719"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1511176644719"
webtalk_transmit -clientid 3026909431 -regid "174170201_174170202_210646199_166" -xml /tp/xph3sle/xph3sle603/Security_lab/AES/synth/vivado/aes_ddr/aes_ddr.sdk/webtalk/usage_statistics_ext_sdk.xml -html /tp/xph3sle/xph3sle603/Security_lab/AES/synth/vivado/aes_ddr/aes_ddr.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /tp/xph3sle/xph3sle603/Security_lab/AES/synth/vivado/aes_ddr/aes_ddr.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
